#!/bin/bash
set -e
DMENU_CMD="dmenu -fn monospace:size=10 -nb #282828 -sb #d69922 -sf #000000" 
CHOICES="LukeSmith
MentalOutlaw
FabioAkita
LinusTechTips
PeperaioHardware
EiNerd
Canal90
DioLinux
DistroTube
DIYPerks
FilmesNostalgicos
CovildeJack
ResumindoAnimes
ResumindoFilmes
ShortCircuit
Tecmundo"

CHOICE=$(printf "$CHOICES" | $DMENU_CMD -p "Select a Channel:")
SWALLOW=

case $CHOICE in
  LukeSmith) ytfzf -D -c youtube-channel https://www.youtube.com/c/LukeSmithxyz ;;
  MentalOutlaw) ytfzf -D -c youtube-channel youtube.com/c/MentalOutlaw ;;
  FabioAkita) ytfzf -D -c youtube-channel https://www.youtube.com/c/FabioAkita1990 ;;
  LinusTechTips) ytfzf -D -c youtube-channel youtube.com/c/LinusTechTips ;;
  PeperaioHardware) ytfzf -D -c youtube-channel youtube.com/c/PeperaioHardwareBR ;;
  EiNerd) ytfzf -D -c youtube-channel youtube.com/c/einerdtv ;;
  Canal90) ytfzf -D -c youtube-channel youtube.com/c/canal90 ;;
  DioLinux) ytfzf -D -c youtube-channel youtube.com/c/DiolinuxBr ;;
  DistroTube) ytfzf -D -c youtube-channel youtube.com/c/DistroTube ;;
  DIYperks) ytfzf -D -c youtube-channel youtube.com/c/DIYPerks ;;
  FilmesNostalgicos) ytfzf -D -c youtube-channel youtube.com/c/FilmesNost%C3%A1lgicos ;;
  CovildeJack) ytfzf -D -c youtube-channel youtube.com/c/13thDeadJack ;;
  ResumindoAnimes) ytfzf -D -c youtube-channel youtube.com/c/EscolhaFatalResumindoAnimes ;;
  ResumindoFilmes) ytfzf -D -c youtube-channel youtube.com/c/ResumindoFilmes ;;
  ShortCircuit) ytfzf -D -c youtube-channel youtube.com/c/ShortCircuit ;;
  Tecmundo) ytfzf -D -c youtube-channel youtube.com/c/tecmundo ;;
  
esac
